import subprocess
from pathlib import Path
from logger import logger


class TerminalThemeManager:
    """Manages color schemes for Alacritty and Kitty terminal emulators."""

    def __init__(self):
        self.home = Path.home()
        self.alacritty_dir = self.home / ".config" / "alacritty"
        self.kitty_dir = self.home / ".config" / "kitty"
        self.fish_dir = self.home / ".config" / "fish"
        self.zsh_dir = self.home / ".config" / "zsh"

    def apply_themes(self, palette: dict, style: str = "Material Pure") -> None:
        """Applies the generated palette to all supported terminal emulators, factoring in style semantics."""
        logger.info(f"Applying terminal themes with style: {style}")
        try:
            self._generate_alacritty_theme(palette, style)
            self._generate_kitty_theme(palette, style)
            self._generate_fish_theme(palette)
            self._generate_zsh_theme(palette)
            logger.info("Terminal themes generated and applied successfully.")
        except Exception as e:
            logger.error(f"Failed to apply terminal themes: {e}")

    def _generate_alacritty_theme(self, palette: dict, style: str) -> None:
        """Generates Alacritty TOML theme file and maps Material You colors, including opacity."""
        if not self.alacritty_dir.exists():
            self.alacritty_dir.mkdir(parents=True, exist_ok=True)

        color_file = self.alacritty_dir / "cachy-colors.toml"

        # Alacritty expects hex colors without alpha, e.g., "#RRGGBB"
        # Mapping Material You palette to generic terminal ANSI colors
        toml_content = f"""# Auto-generated by Adaptive Cachy Beauty Engine
[colors.primary]
background = "{palette.get('background', '#1E1E2E')}"
foreground = "{palette.get('on_background', '#CDD6F4')}"

[colors.cursor]
text = "{palette.get('background', '#1E1E2E')}" # usually invert of foreground
cursor = "{palette.get('color7', '#BAC2DE')}"

[colors.normal]
black   = "{palette.get('color0', '#45475A')}"
red     = "{palette.get('color1', '#F38BA8')}"
green   = "{palette.get('color2', '#A6E3A1')}"
yellow  = "{palette.get('color3', '#F9E2AF')}"
blue    = "{palette.get('color4', '#89B4FA')}"
magenta = "{palette.get('color5', '#F5C2E7')}"
cyan    = "{palette.get('color6', '#94E2D5')}"
white   = "{palette.get('color7', '#BAC2DE')}"

[colors.bright]
black   = "{palette.get('color8', '#585B70')}"
red     = "{palette.get('color9', '#F38BA8')}"
green   = "{palette.get('color10', '#A6E3A1')}"
yellow  = "{palette.get('color11', '#F9E2AF')}"
blue    = "{palette.get('color12', '#89B4FA')}"
magenta = "{palette.get('color13', '#F5C2E7')}"
cyan    = "{palette.get('color14', '#94E2D5')}"
white   = "{palette.get('color15', '#A6ADC8')}"

[window]
"""
        # Inject Opacity
        style = style.lower()
        if "neon glass" in style:
            toml_content += "opacity = 0.75"
        elif "frosted glass" in style:
            toml_content += "opacity = 0.65"
        else:
            toml_content += "opacity = 1.0"

        toml_content += "\n"

        with open(color_file, "w") as f:
            f.write(toml_content)
        logger.debug(f"Generated Alacritty scheme at {color_file}")

        self._ensure_alacritty_import(color_file)

    def _ensure_alacritty_import(self, color_file: Path):
        """Ensures the main alacritty.toml imports our color file."""
        main_config = self.alacritty_dir / "alacritty.toml"
        import_line = f'import = ["~/.config/alacritty/{color_file.name}"]'

        if not main_config.exists():
            with open(main_config, "w") as f:
                f.write(f"{import_line}\n")
            return

        with open(main_config, "r") as f:
            content = f.read()

        if color_file.name not in content:
            # Prepend the import so it overrides defaults but can be overridden by user
            with open(main_config, "w") as f:
                f.write(f"{import_line}\n\n{content}")
            logger.debug("Added cachy-colors import to Alacritty main config.")

    def _generate_kitty_theme(self, palette: dict, style: str) -> None:
        """Generates Kitty conf color scheme and injects transparency based on style."""
        if not self.kitty_dir.exists():
            self.kitty_dir.mkdir(parents=True, exist_ok=True)

        color_file = self.kitty_dir / "cachy-colors.conf"

        conf_content = f"""# Auto-generated by Adaptive Cachy Beauty Engine

foreground              {palette.get('on_background', '#CDD6F4')}
background              {palette.get('background', '#1E1E2E')}
"""
        # Inject Opacity
        style = style.lower()
        if "neon glass" in style:
            conf_content += "background_opacity        0.75\n"
            conf_content += "background_blur           32\n"
        elif "frosted glass" in style:
            conf_content += "background_opacity        0.65\n"
            conf_content += "background_blur           64\n"
        else:
            conf_content += "background_opacity        1.0\n"
            conf_content += "background_blur           0\n"

        conf_content += f"""selection_foreground    {palette.get('background', '#1E1E2E')}
selection_background    {palette.get('color7', '#BAC2DE')}

cursor                  {palette.get('color7', '#BAC2DE')}
cursor_text_color       {palette.get('background', '#1E1E2E')}

url_color               {palette.get('color4', '#89B4FA')}

# black
color0                  {palette.get('color0', '#45475A')}
color8                  {palette.get('color8', '#585B70')}

# red
color1                  {palette.get('color1', '#F38BA8')}
color9                  {palette.get('color9', '#F38BA8')}

# green
color2                  {palette.get('color2', '#A6E3A1')}
color10                 {palette.get('color10', '#A6E3A1')}

# yellow
color3                  {palette.get('color3', '#F9E2AF')}
color11                 {palette.get('color11', '#F9E2AF')}

# blue
color4                  {palette.get('color4', '#89B4FA')}
color12                 {palette.get('color12', '#89B4FA')}

# magenta
color5                  {palette.get('color5', '#F5C2E7')}
color13                 {palette.get('color13', '#F5C2E7')}

# cyan
color6                  {palette.get('color6', '#94E2D5')}
color14                 {palette.get('color14', '#94E2D5')}

# white
color7                  {palette.get('color7', '#BAC2DE')}
color15                 {palette.get('color15', '#A6ADC8')}
"""
        with open(color_file, "w") as f:
            f.write(conf_content)
        logger.debug(f"Generated Kitty scheme at {color_file}")

        self._ensure_kitty_import(color_file)
        self._reload_kitty()

    def _ensure_kitty_import(self, color_file: Path):
        """Ensures the main kitty.conf imports our color file."""
        main_config = self.kitty_dir / "kitty.conf"
        import_line = f"include {color_file.name}"

        if not main_config.exists():
            with open(main_config, "w") as f:
                f.write(f"{import_line}\n")
            return

        with open(main_config, "r") as f:
            content = f.read()

        # Remove existing include if it's not at the end, so we can force it to be the final override
        lines = [
            line
            for line in content.split("\n")
            if line.strip() != import_line and line.strip() != "# Adaptive Cachy Theme"
        ]

        with open(main_config, "w") as f:
            f.write("\n".join(lines))
            f.write(f"\n\n# Adaptive Cachy Theme\n{import_line}\n")

        logger.debug(
            "Ensured cachy-colors include is at the bottom of Kitty main config."
        )

    def _reload_kitty(self):
        """Sends SIGUSR1 to Kitty to gracefully reload config without restarting."""
        try:
            # Using killall is generally safe for user processes
            subprocess.run(
                ["killall", "-USR1", "kitty"], check=False, stderr=subprocess.DEVNULL
            )
            logger.debug("Sent SIGUSR1 to kitty processes for hot-reload.")
        except Exception as e:
            logger.debug(f"Could not reload kitty (might not be running): {e}")

    def _generate_fish_theme(self, palette: dict):
        """Generates and applies a Fish shell color scheme using universal variables."""
        if not self.fish_dir.exists():
            return  # Fish is not installed or configured, skip safely.

        color_file = self.fish_dir / "cachy-colors.fish"

        # Mapping standard fish_color variables using the new ANSI generated palette
        # Format: set -U fish_color_xxx "HEX"
        commands = [
            f'set -U fish_color_normal "{palette.get("on_background", "#CDD6F4")}"',
            f'set -U fish_color_command "{palette.get("color4", "#89B4FA")}"',  # Blue
            f'set -U fish_color_keyword "{palette.get("color5", "#F5C2E7")}"',  # Magenta
            f'set -U fish_color_quote "{palette.get("color3", "#F9E2AF")}"',  # Yellow
            f'set -U fish_color_redirection "{palette.get("color6", "#94E2D5")}"',  # Cyan
            f'set -U fish_color_end "{palette.get("color1", "#F38BA8")}"',  # Red
            f'set -U fish_color_error "{palette.get("color9", "#F38BA8")}"',  # Bright Red
            f'set -U fish_color_param "{palette.get("color7", "#BAC2DE")}"',  # White
            f'set -U fish_color_comment "{palette.get("color8", "#585B70")}"',  # Bright Black (Gray)
            f'set -U fish_color_selection --background="{palette.get("color8", "#585B70")}"',
            f'set -U fish_color_search_match --background="{palette.get("color8", "#585B70")}"',
            f'set -U fish_color_operator "{palette.get("color2", "#A6E3A1")}"',  # Green
            f'set -U fish_color_escape "{palette.get("color10", "#A6E3A1")}"',  # Bright Green
            f'set -U fish_color_autosuggestion "{palette.get("color8", "#585B70")}"',
        ]

        fish_script = "\\n".join(commands) + "\\n"

        # Write to file (optional, but good for debugging and backup)
        with open(color_file, "w") as f:
            f.write("# Auto-generated by Adaptive Cachy Beauty Engine\\n")
            f.write(fish_script.replace("\\n", "\n"))

        # Execute script to trigger Universal Variables broadcast
        try:
            subprocess.run(
                ["fish", "-c", fish_script.replace("\\n", "\n")],
                check=False,
                stderr=subprocess.DEVNULL,
            )
            logger.debug(f"Generated and applied Fish shell schema via {color_file}")
        except Exception as e:
            logger.debug(f"Could not apply Fish scheme (is fish installed?): {e}")

    def _generate_zsh_theme(self, palette: dict):
        """Generates a Zsh color scheme file for syntax highlighting and base terminal colors."""
        if not self.zsh_dir.exists():
            self.zsh_dir.mkdir(parents=True, exist_ok=True)

        color_file = self.zsh_dir / "cachy-colors.zsh"

        # Zsh-syntax-highlighting and base shell variable mapping
        zsh_content = f"""# Auto-generated by Adaptive Cachy Beauty Engine
# Base Colors
export ACB_BACKGROUND="{palette.get('background', '#1E1E2E')}"
export ACB_FOREGROUND="{palette.get('on_background', '#CDD6F4')}"

# ZSH Syntax Highlighting Colors
# These are commonly used by modern zsh-syntax-highlighting themes
ZSH_HIGHLIGHT_STYLES[command]='fg={palette.get("color4", "#89B4FA")}'
ZSH_HIGHLIGHT_STYLES[alias]='fg={palette.get("color6", "#94E2D5")}'
ZSH_HIGHLIGHT_STYLES[builtin]='fg={palette.get("color5", "#F5C2E7")}'
ZSH_HIGHLIGHT_STYLES[function]='fg={palette.get("color4", "#89B4FA")}'
ZSH_HIGHLIGHT_STYLES[keyword]='fg={palette.get("color5", "#F5C2E7")}'
ZSH_HIGHLIGHT_STYLES[string]='fg={palette.get("color3", "#F9E2AF")}'
ZSH_HIGHLIGHT_STYLES[comment]='fg={palette.get("color8", "#585B70")}'
ZSH_HIGHLIGHT_STYLES[error]='fg={palette.get("color1", "#F38BA8")}'
ZSH_HIGHLIGHT_STYLES[path]='fg={palette.get("color6", "#94E2D5")}'

# LS_COLORS Integration (Optional but helpful)
export LS_COLORS="$LS_COLORS:di=01;34:ln=01;36:mh=00:pi=40;33:so=01;35:do=01;35:bd=40;33;01:cd=40;33;01:or=40;31;01:mi=00:su=37;41:sg=30;43:ca=30;41:tw=30;42:ow=34;42:st=37;44:ex=01;32:*.tar=01;31:*.tgz=01;31:*.arc=01;31:*.arj=01;31:*.taz=01;31:*.lha=01;31:*.lz4=01;31:*.lzh=01;31:*.lzma=01;31:*.tlz=01;31:*.txz=01;31:*.tzo=01;31:*.t7z=01;31:*.zip=01;31:*.z=01;31:*.dz=01;31:*.gz=01;31:*.lrz=01;31:*.lz=01;31:*.lzo=01;31:*.xz=01;31:*.zst=01;31:*.tzst=01;31:*.bz2=01;31:*.bz=01;31:*.tbz=01;31:*.tbz2=01;31:*.tz=01;31:*.deb=01;31:*.rpm=01;31:*.jar=01;31:*.war=01;31:*.ear=01;31:*.sar=01;31:*.rar=01;31:*.alz=01;31:*.ace=01;31:*.zoo=01;31:*.cpio=01;31:*.7z=01;31:*.rz=01;31:*.cab=01;31:*.wim=01;31:*.swm=01;31:*.dwm=01;31:*.esd=01;31:*.jpg=01;35:*.jpeg=01;35:*.mjpg=01;35:*.mjpeg=01;35:*.gif=01;35:*.bmp=01;35:*.pbm=01;35:*.pgm=01;35:*.ppm=01;35:*.tga=01;35:*.xbm=01;35:*.xpm=01;35:*.tif=01;35:*.tiff=01;35:*.png=01;35:*.svg=01;35:*.svgz=01;35:*.mng=01;35:*.pcx=01;35:*.mov=01;35:*.mpg=01;35:*.mpeg=01;35:*.m2v=01;35:*.mkv=01;35:*.webm=01;35:*.ogm=01;35:*.mp4=01;35:*.m4v=01;35:*.mp4v=01;35:*.vob=01;35:*.qt=01;35:*.nuv=01;35:*.wmv=01;35:*.asf=01;35:*.rm=01;35:*.rmvb=01;35:*.flc=01;35:*.avi=01;35:*.fli=01;35:*.flv=01;35:*.gl=01;35:*.dl=01;35:*.xcf=01;35:*.xwd=01;35:*.yuv=01;35:*.cgm=01;35:*.emf=01;35:*.ogv=01;35:*.ogx=01;35:*.aac=00;36:*.au=00;36:*.flac=00;36:*.m4a=00;36:*.mid=00;36:*.midi=00;36:*.mka=00;36:*.mp3=00;36:*.mpc=00;36:*.ogg=00;36:*.ra=00;36:*.wav=00;36:*.oga=00;36:*.opus=00;36:*.spx=00;36:*.xspf=00;36:"
"""
        with open(color_file, "w") as f:
            f.write(zsh_content)
        logger.debug(f"Generated Zsh scheme at {color_file}")

        self._ensure_zsh_import(color_file)

    def _ensure_zsh_import(self, color_file: Path):
        """Ensures that the main .zshrc imports our generated color file."""
        zshrc = Path.home() / ".zshrc"
        import_line = f'source "{color_file}"'

        if not zshrc.exists():
            # If for some reason .zshrc doesn't exist, we don't want to break things
            return

        with open(zshrc, "r") as f:
            content = f.read()

        if str(color_file) not in content:
            # Append the import at the end of .zshrc
            with open(zshrc, "a") as f:
                f.write(f"\n# Adaptive Cachy Beauty Theme\n[[ -f {color_file} ]] && {import_line}\n")
            logger.debug(f"Added cachy-colors source to {zshrc}")
