[General]
# This background will be overridden by our daemon dynamically
background=/var/lib/adaptive-cachy/background.jpg
type=image

# These colors will be overridden by our daemon in /var/lib/adaptive-cachy/colors.conf
# We default to something dark and neutral fallback
primary=#00e0fe
on_primary=#005f65
primary_container=#002022
on_primary_container=#aceef4
secondary=#006574
background_color=#001115
on_background=#b7eefc
surface=#001115
surface_variant=#002a32
error=#ff716c
